apiVersion: v1
kind: Pod
metadata:
  name: janus
  labels:
    app: janus
spec:
  containers:
    - name: janus
      image: sergbs/janus
      imagePullPolicy: IfNotPresent
      env:
        - name: JANUS_SERVER
          value: https://192.168.4.134:8089/janus
      ports:
        - containerPort: 443
  restartPolicy: Always
  imagePullSecrets:
    - name: regcred
